'use strict';
// Render .center-ai/generated/*.md — CLI ghi lại mỗi lần chạy, KHÔNG đụng gì ngoài thư
// mục này (Q24.6). company.md/team.md/project.md để trống có ghi chú rõ ràng ở MVP1 pilot
// (chưa có nguồn dữ liệu company/team-level thật — không giả vờ có dữ liệu không tồn tại).
const fs = require('fs');
const path = require('path');

function generatedDir(gitRoot) {
  return path.join(gitRoot, '.center-ai', 'generated');
}

function writePlaceholder(gitRoot, filename, note) {
  const dir = generatedDir(gitRoot);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, filename);
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, `<!-- ${note} -->\n`);
  }
}

function renderTaskMd(gitRoot, { task, project }) {
  const dir = generatedDir(gitRoot);
  fs.mkdirSync(dir, { recursive: true });
  const lines = [
    `# Task: ${task.title}`,
    '',
    `Project: ${project ? project.name : task.project_id}`,
    `Status: ${task.status}`,
    '',
  ];
  fs.writeFileSync(path.join(dir, 'task.md'), lines.join('\n') + '\n');
}

function renderCheckpointMd(gitRoot, { latestHandoff, contextNotes }) {
  const dir = generatedDir(gitRoot);
  fs.mkdirSync(dir, { recursive: true });
  const lines = [`# Handoff & context gần nhất`, ''];

  if (latestHandoff) {
    lines.push(`## Bàn giao từ ${latestHandoff.from_employee_name} (${new Date(latestHandoff.created_at).toLocaleString()})`, '');
    lines.push('**Đã hoàn thành:**');
    lines.push(...summaryList(latestHandoff.summary));
    lines.push('', '**Còn lại / bước tiếp theo:**');
    lines.push(...jsonListToMd(latestHandoff.next_steps));
    lines.push('', '**Vấn đề mở / BA feedback chưa xử lý:**');
    lines.push(...jsonListToMd(latestHandoff.open_issues));
  } else {
    lines.push('_Chưa có handoff nào cho task này — bạn là người đầu tiên làm._');
  }

  if (contextNotes && contextNotes.length) {
    lines.push('', '## Ghi chú khác (requirement / decision / BA feedback)');
    for (const note of contextNotes) {
      // Confidence (Q15) — tính sẵn ở Control Plane, CLI chỉ hiển thị, không tự tính lại.
      const confidenceTxt = typeof note.confidence === 'number' ? ` _(${note.confidence_label})_` : '';
      lines.push(`- [${note.type}] ${note.content}${confidenceTxt}`);
    }
  }

  fs.writeFileSync(path.join(dir, 'checkpoint.md'), lines.join('\n') + '\n');
}

function summaryList(summary) {
  return String(summary || '')
    .split('\n')
    .filter(Boolean)
    .map((l) => `- ${l}`);
}
function jsonListToMd(arr) {
  if (!arr || !arr.length) return ['- (không có)'];
  return arr.map((item) => `- ${typeof item === 'string' ? item : JSON.stringify(item)}`);
}

const MARKER_START = '<!-- BEGIN CENTER-AI CONTEXT (do not edit manually, generated by `company-ai init`) -->';
const MARKER_END = '<!-- END CENTER-AI CONTEXT -->';
const MARKER_BLOCK = [
  MARKER_START,
  '@.center-ai/generated/company.md',
  '@.center-ai/generated/team.md',
  '@.center-ai/generated/project.md',
  '@.center-ai/generated/task.md',
  '@.center-ai/generated/checkpoint.md',
  MARKER_END,
  '',
].join('\n');

function ensureClaudeMdMarker(gitRoot) {
  const file = path.join(gitRoot, 'CLAUDE.md');
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (existing.includes(MARKER_START)) return { changed: false };
  const next = existing ? existing.replace(/\s*$/, '\n\n') + MARKER_BLOCK : MARKER_BLOCK;
  fs.writeFileSync(file, next);
  return { changed: true };
}

module.exports = { generatedDir, writePlaceholder, renderTaskMd, renderCheckpointMd, ensureClaudeMdMarker };
