'use strict';
// Ghi .center-ai/generated/*.md — CLI ghi lại mỗi lần chạy, KHÔNG đụng gì ngoài thư mục này (Q24.6).
//
// TRƯỚC ĐÂY file này TỰ DỰNG nội dung 5 file .md. Nay nội dung do Control Plane render
// (spike/control-plane/context-render.js) và CLI chỉ ghi xuống đĩa những chuỗi nhận được.
// Lý do: dashboard cũng phải hiện đúng nội dung AI nhận — nếu mỗi bên tự render sẽ có 2 bộ logic
// lệch nhau, dashboard hiện 1 đằng AI đọc 1 nẻo, hỏng đúng thứ giá trị nhất của sản phẩm.
// Giờ cả 2 cùng gọi GET /v1/context/bundle -> 1 nguồn sự thật duy nhất.
const fs = require('fs');
const path = require('path');

function generatedDir(gitRoot) {
  return path.join(gitRoot, '.center-ai', 'generated');
}

// Tên file trên đĩa <- khoá tương ứng trong bundle. Đúng 5 file mà CLAUDE.md trỏ tới
// (xem MARKER_BLOCK bên dưới) — thêm/bớt ở đây phải sửa cả marker.
const BUNDLE_FILES = {
  'company.md': 'company_md',
  'team.md': 'team_md',
  'project.md': 'project_md',
  'task.md': 'task_md',
  'checkpoint.md': 'checkpoint_md',
};

function writeBundle(gitRoot, files) {
  const dir = generatedDir(gitRoot);
  fs.mkdirSync(dir, { recursive: true });
  for (const [filename, key] of Object.entries(BUNDLE_FILES)) {
    // Thiếu khoá nào thì ghi rõ là thiếu, KHÔNG bỏ qua im lặng — file cũ còn sót lại trên đĩa
    // sẽ khiến AI đọc nội dung lỗi thời mà không ai biết.
    const content = typeof files[key] === 'string' ? files[key] : `<!-- Control Plane không trả về ${key} -->\n`;
    fs.writeFileSync(path.join(dir, filename), content);
  }
}

const MARKER_START = '<!-- BEGIN CENTER-AI CONTEXT (do not edit manually, generated by `company-ai init`) -->';
const MARKER_END = '<!-- END CENTER-AI CONTEXT -->';
const MARKER_BLOCK = [
  MARKER_START,
  '@.center-ai/generated/company.md',
  '@.center-ai/generated/team.md',
  '@.center-ai/generated/project.md',
  '@.center-ai/generated/task.md',
  '@.center-ai/generated/checkpoint.md',
  MARKER_END,
  '',
].join('\n');

function ensureClaudeMdMarker(gitRoot) {
  const file = path.join(gitRoot, 'CLAUDE.md');
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (existing.includes(MARKER_START)) return { changed: false };
  const next = existing ? existing.replace(/\s*$/, '\n\n') + MARKER_BLOCK : MARKER_BLOCK;
  fs.writeFileSync(file, next);
  return { changed: true };
}

module.exports = { generatedDir, writeBundle, ensureClaudeMdMarker };
